name: Deploy project Practice Tests
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NodeJs Setup
        uses: actions/setup-node@v2
        with:
          node-version: 20.x  # Or a compatible version

      - name: Install dependencies
        run: npm install

      - name: App Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS S3
        run: |
          if [[ -d build ]]; then
            aws s3 sync dist/ s3://practice-tests-practitioner/ --delete
          else
            echo "Build directory not found. Check the build process logs."
            exit 1
          fi

      

            
